name: GitHub Metrics Report

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3 AM UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: masuvro  # Replace with your GitHub username
          filename: metrics.svg
          base: activity, community, repositories, metadata
